default: &default
  adapter: postgresql
  host: 127.0.0.1
  username: <%= ENV.fetch('PG_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('PG_PASSWORD', '123456') %>
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: digital_assets_api_development
